ARG ARCH_IMG

FROM ${ARCH_IMG}

ENV PCX_DISCORDBOT true

RUN set -eux; \
    apk add --no-cache \
# Redbot dependencies
        build-base \
        git \
        openjdk8-jre \
        unzip

COPY root/ /

VOLUME /data

CMD ["/start-redbot.sh"]

LABEL maintainer="Ryan Foster <phasecorex@gmail.com>"
