ARG ARCH_IMG

FROM alpine
ARG DRONE_COMMIT_SHA
RUN : "${DRONE_COMMIT_SHA:?Build argument 'DRONE_COMMIT_SHA' needs to be set and non-empty.}"



FROM ${ARCH_IMG}

RUN set -eux; \
    apk add --no-cache \
# Redbot dependencies
        build-base \
        git \
        openjdk8-jre \
        unzip

COPY root/ /

ARG DRONE_COMMIT_SHA
ENV PCX_DISCORDBOT_COMMIT ${DRONE_COMMIT_SHA}

VOLUME /data

CMD ["/start-redbot.sh"]

LABEL maintainer="Ryan Foster <phasecorex@gmail.com>"
