ARG ARCH_IMG
FROM ${ARCH_IMG}

RUN set -eux; \
    apt-get update; \
    apt-get install -y --no-install-recommends \
# Install popular cog dependencies (python)
    # wand
        libmagickwand-dev \
    # python-aalib
        libaa1-dev \
# Install popular cog dependencies (programs)
        ffmpeg \
    ; \
    rm -rf /var/lib/apt/lists/*;
