FROM phasecorex/user-python:3.7-alpine

MAINTAINER Ryan Foster <phasecorex@gmail.com>

RUN set -eux; \
    apk add --no-cache \
# Redbot dependencies
        gcc \
        git \
        musl-dev \
        openjdk8-jre \
        unzip

COPY root/ /

VOLUME /data

CMD ["/start-redbot.sh"]
